<?php

declare(strict_types=1);

namespace Nowo\DoctrineEncryptBundle\Encryptors;

use ParagonIE\Halite\Alerts\CannotPerformOperation;
use ParagonIE\Halite\KeyFactory;
use ParagonIE\Halite\Symmetric\Crypto;
use ParagonIE\Halite\Symmetric\EncryptionKey;
use ParagonIE\HiddenString\HiddenString;
use RangeException;
use RuntimeException;

use function sprintf;

/**
 * Encryptor implementation using paragonie/halite (symmetric authenticated encryption).
 *
 * The secret key can be read from a file (hex-encoded) or from string content (e.g. env var).
 * If the key file does not exist, a new key is generated and saved.
 *
 * @author Michael de Groot <specamps@gmail.com>
 */
final class HaliteEncryptor implements EncryptorInterface
{
    private ?EncryptionKey $encryptionKey = null;
    private readonly ?string $keyContent;

    /**
     * @param string $keyFile path to the key file (ignored when $keyContent is set)
     * @param string|null $keyContent Optional key value (e.g. from env). When set, $keyFile is not read.
     */
    public function __construct(private readonly string $keyFile, ?string $keyContent = null)
    {
        $this->keyContent = $keyContent !== null && $keyContent !== '' ? $keyContent : null;
    }

    /**
     * Encrypts plain text using the Halite key.
     *
     * @param string $data Plain text to encrypt
     *
     * @return string Ciphertext
     */
    public function encrypt(string $data): string
    {
        return Crypto::encrypt(new HiddenString($data), $this->getKey());
    }

    /**
     * Decrypts ciphertext using the Halite key.
     *
     * @param string $data Ciphertext to decrypt
     *
     * @return string Plain text
     */
    public function decrypt(string $data): string
    {
        $data = Crypto::decrypt($data, $this->getKey());

        $data = $data->getString();

        return $data;
    }

    /**
     * Returns the Halite encryption key, loading from file or env content; creates the key file if missing.
     */
    private function getKey(): EncryptionKey
    {
        if (!$this->encryptionKey instanceof EncryptionKey) {
            if ($this->keyContent !== null) {
                $this->encryptionKey = $this->loadKeyFromString(trim($this->keyContent));

                return $this->encryptionKey;
            }
            if ($this->keyFile === '') {
                throw new RuntimeException('The encryption key environment variable is not set. Run "php bin/console doctrine:encrypt:generate-secret-key" to get the key value, then set it in your .env or environment.');
            }
            try {
                $this->normalizeKeyFile();
                $this->encryptionKey = KeyFactory::loadEncryptionKey($this->keyFile);
            } catch (CannotPerformOperation) {
                $this->encryptionKey = KeyFactory::generateEncryptionKey();
                KeyFactory::save($this->encryptionKey, $this->keyFile);
            } catch (RangeException $e) {
                throw new RuntimeException(sprintf('Invalid Halite key file at "%s": key must be hex-encoded (e.g. generated by doctrine:encrypt:generate-secret-key). Error: %s', $this->keyFile, $e->getMessage()), 0, $e);
            }
        }

        return $this->encryptionKey;
    }

    /**
     * Loads the encryption key from string content (e.g. from env).
     * Halite only supports loading from file, so a temporary file is used.
     *
     * @param string $content Hex-encoded key content
     */
    private function loadKeyFromString(string $content): EncryptionKey
    {
        $tmp = tempnam(sys_get_temp_dir(), 'halite_key_');
        if ($tmp === false) {
            throw new RuntimeException('Could not create temp file for key.');
        }
        try {
            file_put_contents($tmp, $content);

            return KeyFactory::loadEncryptionKey($tmp);
        } finally {
            @unlink($tmp);
        }
    }

    /**
     * Trims leading/trailing whitespace in the key file so Halite's hex decoder does not fail.
     */
    private function normalizeKeyFile(): void
    {
        if (!is_file($this->keyFile) || !is_readable($this->keyFile)) {
            return;
        }
        $content = (string) file_get_contents($this->keyFile);
        $trimmed = trim($content);
        if ($trimmed !== $content) {
            file_put_contents($this->keyFile, $trimmed);
        }
    }
}
