services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctrine-encrypt-demo-symfony7-php
    working_dir: /app
    restart: unless-stopped
    ports:
      - "${PORT:-8007}:80"
    volumes:
      - .:/app
      - ../..:/var/doctrine-encrypt-bundle
      - composer-cache:/root/.composer/cache
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=dev
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
    networks:
      - doctrine-encrypt-demo-network

volumes:
  composer-cache:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
    driver: local

networks:
  doctrine-encrypt-demo-network:
    driver: bridge
