#!/bin/sh
set -e


# FRANKENPHP_MODE: classic | worker (REQ-DEMO-010). Default: worker.
# Set via .env / Compose only — not baked into the image ENV.
MODE="${FRANKENPHP_MODE:-worker}"
case "$MODE" in
	classic)
		if [ -f /app/Caddyfile.dev ]; then
			cp /app/Caddyfile.dev /etc/caddy/Caddyfile
		elif [ -f /etc/frankenphp/Caddyfile.dev ]; then
			cp /etc/frankenphp/Caddyfile.dev /etc/frankenphp/Caddyfile
		fi
		;;
	worker)
		if [ -f /app/Caddyfile ]; then
			cp /app/Caddyfile /etc/caddy/Caddyfile
		fi
		# else keep image default Caddyfile (worker enabled)
		;;
	*)
		echo "Unknown FRANKENPHP_MODE=$MODE (expected classic|worker)" >&2
		exit 1
		;;
esac
echo "FrankenPHP mode: $MODE"


mkdir -p /app/var/cache /app/var/log /app/var
chmod -R 777 /app/var 2>/dev/null || true

if [ ! -f /app/vendor/autoload_runtime.php ]; then
	echo "📦 vendor not found, running composer install..."
	if ! composer install --no-interaction --working-dir=/app; then
		echo "❌ composer install failed (composer.json / composer.lock out of sync?)."
		echo "   From host: make install   or   docker compose run --rm --entrypoint sh php -c 'composer update --no-interaction'"
		echo "   Waiting so the container stays up for debugging (no restart loop)..."
		exec tail -f /dev/null
	fi
	echo "✅ Composer install done."
fi

if [ -d /app/vendor ]; then
	echo "📦 Creating database and schema if needed..."
	php /app/bin/console doctrine:database:create --if-not-exists --no-interaction 2>/dev/null || true
	php /app/bin/console doctrine:schema:update --force --no-interaction 2>/dev/null || true
	# Ensure .env exists (e.g. from volume mount)
	if [ ! -f /app/.env ]; then
		cp /app/.env.example /app/.env 2>/dev/null || true
	fi
	echo "📦 Generating encryption keys (files + env)..."
	KEYGEN_OUT=$(php /app/bin/console doctrine:encrypt:generate-secret-key 2>/dev/null || true)
	echo "$KEYGEN_OUT"
	# Extract Halite key from output and add APP_ENCRYPT_KEY to .env if not set
	KEY=$(echo "$KEYGEN_OUT" | grep -E '^[a-f0-9]{100,}$' | head -1)
	if [ -n "$KEY" ] && ! grep -q '^APP_ENCRYPT_KEY=.' /app/.env 2>/dev/null; then
		echo "" >> /app/.env
		echo "# Doctrine Encrypt Bundle - key for personal_data (generated by doctrine:encrypt:generate-secret-key)" >> /app/.env
		echo "APP_ENCRYPT_KEY=$KEY" >> /app/.env
		echo "✅ APP_ENCRYPT_KEY added to .env"
	fi
	echo "📦 Loading fixtures..."
	php /app/bin/console doctrine:fixtures:load --no-interaction 2>/dev/null || true
	echo "✅ Database, keys and fixtures ready."
fi

exec frankenphp run --config /etc/frankenphp/Caddyfile --adapter caddyfile
