services:
  _defaults:
    autowire: true
    autoconfigure: true

  Nowo\DoctrineEncryptBundle\Command\:
    resource: '../../Command/*'
    exclude: '../../Command/AbstractCommand.php'

  Nowo\DoctrineEncryptBundle\Command\DoctrineEncryptDatabaseCommand:
    arguments:
      $defaultEncryptor: '@nowo_doctrine_encrypt.encryptor'
      $encryptorRegistry: '@nowo_doctrine_encrypt.encryptor_registry'

  Nowo\DoctrineEncryptBundle\Command\DoctrineDecryptDatabaseCommand:
    arguments:
      $defaultEncryptor: '@nowo_doctrine_encrypt.encryptor'
      $encryptorRegistry: '@nowo_doctrine_encrypt.encryptor_registry'

  Nowo\DoctrineEncryptBundle\Command\GenerateSecretKeyCommand:
    arguments:
      $kernel: '@kernel'
      $keyPaths: '%nowo_doctrine_encrypt.key_paths%'

  nowo_doctrine_encrypt.encryptor_registry:
    class: Nowo\DoctrineEncryptBundle\Encryptors\EncryptorRegistry
    arguments: [[], 'default']
    # Arguments are overwritten by DoctrineEncryptExtension (legacy: one encryptor; configs: map of encryptors)

  Nowo\DoctrineEncryptBundle\Encryptors\EncryptorRegistry: '@nowo_doctrine_encrypt.encryptor_registry'
  
  Nowo\DoctrineEncryptBundle\Encryptors\EncryptorInterface: '@nowo_doctrine_encrypt.encryptor'

  nowo_doctrine_encrypt.encryptor:
    class: "%nowo_doctrine_encrypt.encryptor_class_name%"
    arguments:
      - "%nowo_doctrine_encrypt.secret_key_path%"

  nowo_doctrine_attribute_reader:
    class: Nowo\DoctrineEncryptBundle\Mapping\AttributeReader

  Nowo\DoctrineEncryptBundle\Mapping\AttributeReader: '@nowo_doctrine_attribute_reader'

  Nowo\DoctrineEncryptBundle\Subscribers\:
    resource: '../../Subscribers/*'

  nowo_doctrine_encrypt.orm_subscriber:
    class: Nowo\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
    arguments: ["@nowo_doctrine_encrypt.encryptor_registry"]
    tags:
      - { name: 'doctrine.event_listener', event: 'postUpdate', priority: 500, connection: 'default' }
      - { name: 'doctrine.event_listener', event: 'preUpdate', priority: 500, connection: 'default' }
      - { name: 'doctrine.event_listener', event: 'postLoad', priority: 500, connection: 'default' }
      - { name: 'doctrine.event_listener', event: 'onFlush', priority: 500, connection: 'default' }
      - { name: 'doctrine.event_listener', event: 'preFlush', priority: 500, connection: 'default' }
      - { name: 'doctrine.event_listener', event: 'postFlush', priority: 500, connection: 'default' }

  nowo_doctrine_encrypt.subscriber:
    alias: nowo_doctrine_encrypt.orm_subscriber

  Nowo\DoctrineEncryptBundle\Twig\:
    resource: '../../Twig/*'

  Nowo\DoctrineEncryptBundle\Util\:
    resource: '../../Util/*'
